import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { motion } from 'framer-motion';
import { useWizard } from '../context/WizardContext';
import { GuestChip } from './GuestChip';
export function SummaryCard({ person }) {
    const { guests, computation } = useWizard();
    const guest = guests.find((g) => g.id === person.guestId);
    const displayName = guest?.name || person.guestId;
    const isPayer = computation?.payerId === person.guestId;
    return (_jsxs(motion.div, { className: "glass-card p-6", initial: { opacity: 0, y: 20 }, animate: { opacity: 1, y: 0 }, whileHover: { scale: 1.02 }, transition: { duration: 0.2 }, children: [_jsxs("div", { className: "mb-4 flex items-center justify-between", children: [_jsx("h3", { className: "text-xl font-semibold text-slate-200", children: displayName }), guest && _jsx(GuestChip, { guestId: guest.id, name: guest.name, isSelected: true, onToggle: () => { }, showCheckmark: false })] }), _jsxs("div", { className: "space-y-3", children: [_jsxs("div", { className: "flex items-center justify-between text-sm", children: [_jsx("span", { className: "text-slate-400", children: "Items" }), _jsxs("span", { className: "font-medium text-slate-200", children: ["$", (person.itemsTotalCents / 100).toFixed(2)] })] }), _jsxs("div", { className: "flex items-center justify-between text-sm", children: [_jsx("span", { className: "text-slate-400", children: "Tax" }), _jsxs("span", { className: "font-medium text-slate-200", children: ["$", (person.taxCents / 100).toFixed(2)] })] }), _jsxs("div", { className: "flex items-center justify-between text-sm", children: [_jsx("span", { className: "text-slate-400", children: "Tip" }), _jsxs("span", { className: "font-medium text-slate-200", children: ["$", (person.tipCents / 100).toFixed(2)] })] }), _jsx("div", { className: "border-t border-slate-800 pt-3", children: _jsxs("div", { className: "flex items-center justify-between", children: [_jsx("span", { className: "text-base font-semibold text-slate-200", children: "Total" }), _jsxs("span", { className: "text-2xl font-bold text-brand", children: ["$", (person.totalCents / 100).toFixed(2)] })] }) }), person.owedToPayerCents > 0 && (_jsx(motion.div, { className: "mt-3 rounded-lg bg-warning/10 border border-warning/30 p-2", initial: { opacity: 0 }, animate: { opacity: 1 }, transition: { delay: 0.2 }, children: _jsxs("p", { className: "text-xs text-warning text-center", children: ["Owes $", (person.owedToPayerCents / 100).toFixed(2)] }) })), isPayer && (_jsx(motion.div, { className: "mt-3 rounded-lg bg-success/10 border border-success/30 p-2", initial: { opacity: 0 }, animate: { opacity: 1 }, transition: { delay: 0.2 }, children: _jsx("p", { className: "text-xs text-success text-center", children: "Paid the bill" }) }))] })] }));
}
