import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { SummaryCard } from '../components/SummaryCard';
import { DebtsTable } from '../components/DebtsTable';
import { ExportButtons } from '../components/ExportButtons';
import { useWizard } from '../context/WizardContext';
import { staggerContainer } from '../lib/animations';
export default function ReviewPage() {
    const { setStep, computation } = useWizard();
    useEffect(() => {
        // Scroll to top when page loads
        window.scrollTo({ top: 0, behavior: 'smooth' });
    }, []);
    return (_jsxs(motion.section, { className: "space-y-6", initial: { opacity: 0, y: 20 }, animate: { opacity: 1, y: 0 }, exit: { opacity: 0, y: -20 }, transition: { duration: 0.3 }, children: [_jsxs("header", { children: [_jsx("p", { className: "text-sm uppercase tracking-widest text-slate-400", children: "Step 3 of 3" }), _jsx("h1", { className: "text-2xl font-semibold text-slate-200", children: "Review & Send" }), _jsx("p", { className: "mt-2 text-sm text-slate-400", children: "Review the split summary and export or send the results to your guests." })] }), _jsx(AnimatePresence, { mode: "wait", children: !computation ? (_jsx(motion.div, { initial: { opacity: 0 }, animate: { opacity: 1 }, exit: { opacity: 0 }, className: "rounded-lg border border-warning/50 bg-warning/10 p-4", role: "alert", children: _jsxs("div", { className: "flex items-start gap-3", children: [_jsx("svg", { className: "h-5 w-5 text-warning flex-shrink-0 mt-0.5", fill: "none", viewBox: "0 0 24 24", stroke: "currentColor", children: _jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", strokeWidth: 2, d: "M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" }) }), _jsxs("div", { children: [_jsx("p", { className: "text-sm font-medium text-warning", children: "Missing computation" }), _jsx("p", { className: "mt-1 text-xs text-warning/80", children: "Go back and complete assignments to see the review." })] })] }) }, "no-computation")) : (_jsxs(motion.div, { variants: staggerContainer, initial: "initial", animate: "animate", className: "space-y-6", children: [_jsxs("div", { children: [_jsx("h2", { className: "mb-4 text-lg font-semibold text-slate-200", children: "Summary by Person" }), _jsx("div", { className: "grid gap-4 sm:grid-cols-2 lg:grid-cols-3", children: computation.perPerson.map((person, index) => (_jsx(motion.div, { initial: { opacity: 0, y: 20 }, animate: { opacity: 1, y: 0 }, transition: { delay: index * 0.1 }, children: _jsx(SummaryCard, { person: person }) }, person.guestId))) })] }), _jsxs("div", { children: [_jsx("h2", { className: "mb-4 text-lg font-semibold text-slate-200", children: "Debts" }), _jsx(DebtsTable, { data: computation })] }), _jsxs("div", { children: [_jsx("h2", { className: "mb-4 text-lg font-semibold text-slate-200", children: "Export & Share" }), _jsx(ExportButtons, {})] })] }, "computation")) }), _jsxs("div", { className: "flex justify-between pt-4 border-t border-slate-800", children: [_jsx(motion.button, { className: "btn-secondary touch-target", onClick: () => setStep(1), whileHover: { scale: 1.05 }, whileTap: { scale: 0.95 }, "aria-label": "Go back to match items", children: "Back" }), _jsx(motion.button, { className: "btn-primary touch-target", onClick: () => setStep(0), whileHover: { scale: 1.05 }, whileTap: { scale: 0.95 }, "aria-label": "Finish and start over", children: "Finish" })] })] }));
}
